version: '3.8'
services:
  chatgpt-proxy-node:
    image: hanglegehang/chatgpt-proxy-node:latest
    restart: always
    container_name: chatgpt-proxy-node
    ports:
      - 8100:8100
    environment:
      TZ: Asia/Shanghai # 指定时区

    volumes:
      - ./config.yaml:/app/config.yaml
    labels:
      - "com.centurylinklabs.watchtower.scope=hanglegehang-chatgpt-proxy-node"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope hanglegehang-chatgpt-proxy-node --cleanup --interval 600
    restart: always
    environment:
      - TZ=Asia/Shanghai
    labels:
      - "com.centurylinklabs.watchtower.scope=hanglegehang-chatgpt-proxy-node"